name: ansible-install
run-name: "Testing Ansible install after commit \"${{ github.event.head_commit.message }}\""
on:
  push:
  workflow_dispatch:
jobs:
  install-seek-from-ansible:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        #os: [ubuntu-18.04,ubuntu-20.04,ubuntu-22.04,ubuntu-latest]
        os: [ubuntu-20.04]

    services:
      mysql:
          image: mysql:8.0.21
          env:
              MYSQL_ALLOW_EMPTY_PASSWORD: yes
              MYSQL_ROOT_PASSWORD: ''
              MYSQL_DATABASE: test
          ports:
            - 3306:3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure ansible for local install
        run: |
          sed -i '/vault_password_file/d' ansible.cfg
          sed -i '/ssh_connection/d' ansible.cfg
          sed -i '/pipelining/d' ansible.cfg
          sed -i 's/\- hosts\: \[servers\]/\- hosts\: localhost/g' Deploy-SEEK.yml
          sed -i '/\- hosts\: localhost/a \ \ connection\: local' Deploy-SEEK.yml
          sed -i 's/user_var\: username/user_var\: runner/' group_vars/vars.yml
          sed -i 's/git_dest\: \/home\/username/git_dest\: \/home\/runner\/work/' group_vars/vars.yml
          sed -i '/sql_user\: sql_username/a sql_password: mysqlpassword' group_vars/vars.yml

      - name: Prepares system for ansible install
        run: |
          sudo apt install acl -y

      - name: Install SEEK through ansible
        run: ansible-playbook Deploy-SEEK.yml --skip-tags database

      - name: Configures database
        run: |
          sed -i '/login_unix_socket/d' Deploy-SEEK.yml
          cp /home/runner/work/SEEK/config/database.default.yml /home/runner/work/SEEK/config/database.yml
          sed -i '/password\: mysqlpassword/a \ \ port\: 3306' /home/runner/work/SEEK/config/database.yml
          sed -i '/password\: mysqlpassword/a \ \ host\: 127.0.0.1' /home/runner/work/SEEK/config/database.yml
          sed -i 's/mysqluser/root/g' /home/runner/work/SEEK/config/database.yml
          sed -i 's/mysqlpassword//g' /home/runner/work/SEEK/config/database.yml
          echo 'This is the database configuration in database.yml:'
          cat /home/runner/work/SEEK/config/database.yml
          cd /home/runner/work/SEEK && bash -lc 'bundle exec rake db:setup'

      # - name: Setup SEEK database
      #   run: ansible-playbook Deploy-SEEK.yml --tags database
      #   continue-on-error: true

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Runs seek unit tests
        run: |
          cd /home/runner/work/SEEK && bash -lc 'bundle exec rails test tests/unit'
      
      - name: Runs seek integration tests
        run: |
          cd /home/runner/work/SEEK && bash -lc 'bundle exec rails test tests/integration'

      - name: Runs seek functional tests
        run: |
          cd /home/runner/work/SEEK && bash -lc 'bundle exec rails test tests/functional'